export class CodigosErrorServicio{
  static  USUARIO_NO_EXISTE= 'USUARIO_NO_EXISTE';
  static EXISTE_APLICACION_A_OFERTA='EXISTE_APLICACION_A_OFERTA';
  static APLICACION_NO_EXISTE= 'APLICACION_NO_EXISTE';
  static FECHA_INICIO_INVALIDA='FECHA_INICIO_INVALIDA';
  static FECHA_FIN_INVALIDA = 'FECHA_FIN_INVALIDA';
}
