export class CodigosErrorServicio{
  static  USUARIO_NO_EXISTE= 'USUARIO_NO_EXISTE';
  static EXISTE_APLICACION_A_OFERTA='EXISTE_APLICACION_A_OFERTA';
  static APLICACION_NO_EXISTE= 'APLICACION_NO_EXISTE';

}
